### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by myh7754** [AlphaMaleClub/UCMC#22]
### docker-compose.yml

```
services:
  rabbitmq:
    build:
      context: ./                # 현재 디렉토리 (Dockerfile 있는 위치)
      dockerfile: Dockerfile-rabbitMQ   # Dockerfile 파일명
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ 관리 UI (http://localhost:15672)
      - "5672:5672"    # 기본 AMQP 포트 (Spring 등에서 사용하는 포트)
      - "61613:61613"  # STOMP 포트 (WebSocket용 브로커 릴레이)
```
